theme: jekyll-theme-minimal
title: JetStream
description: JetStream delivers a centralized control plane that simplifies and secures the entire AI stack through unified policy orchestration by our security AI engine.  
We provide deep visibility into AI agents, models, agent to agent activities, AI assistance and user activity—enabling intelligent access decisions and continuous policy enforcement at runtime security
